{
	"name": "IcanhazdadjokeDotCom",
	"version": "1.0.24",
	"icon": "far fa-grin-beam-sweat",
	"category": "entertainment",
	"author": "Psychokiller1888",
	"maintainers": ["maxbachmann", "Jierka", "philipp2310"],
	"desc": "Get a random dad joke on demand!",
	"aliceMinVersion": "1.0.0-a4",
	"systemRequirements": [],
	"pipRequirements": [],
	"conditions": {
		"lang": [
			"en"
		],
		"online": true
	}
}
